services:
    nextjs:
        build: .
        image: xvreed/equip:latest
        container_name: equipmentmanager-ava
        command: npm run dev
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        env_file:
            - .env.local
        working_dir: /app
